### ISSUE TITLE
move adding to actions to the plugin definition phase

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-github-provider#6]
`add_actions` should not be called here: https://github.com/senecajs/seneca-github-provider/blob/main/src/github-provider.ts#L83

Instead it should occur here: https://github.com/senecajs/seneca-github-provider/blob/main/src/github-provider.ts#L27

You need a reference to an initialized Octokit instance of course, but you have it already:
https://github.com/senecajs/seneca-github-provider/blob/main/src/github-provider.ts#L23

Seneca completes are plugin prepare actions before executing anything else, so no entity actions will execute until octokit is ready.

**Comment by guhmerces** [comment]
Hey Richard. I linked a PR to this issue. I couldn't accomplish this task exactly the way we talked because I didn't find a proper way to get around the needing of the callback here: https://github.com/senecajs/seneca-github-provider/blob/main/src/github-provider.ts#L44

I tried a alternative path: resolving the callback inside the actions called by seneca.
